version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: cleantsapi
    image: node:14
    working_dir: /usr/src/clean-ts-api
    restart: always
    command: bash -c "npm install --only=prod"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist:/usr/src/clean-ts-api/dist/
      - ./package.json:/usr/src/clean-ts-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
